// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classes.sql

package db

import (
	"context"
)

const createClass = `-- name: CreateClass :one
INSERT INTO classes (name, homeroom_teacher_id)
VALUES (?, ?)
RETURNING id, name, homeroom_teacher_id, created_at, updated_at
`

type CreateClassParams struct {
	Name              string `json:"name"`
	HomeroomTeacherID *int64 `json:"homeroom_teacher_id"`
}

func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, createClass, arg.Name, arg.HomeroomTeacherID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HomeroomTeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :one
DELETE FROM classes
WHERE id = ?
RETURNING id, name, homeroom_teacher_id, created_at, updated_at
`

func (q *Queries) DeleteClass(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, deleteClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HomeroomTeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClass = `-- name: GetClass :one
SELECT id, name, homeroom_teacher_id, created_at, updated_at FROM classes
WHERE id = ?
LIMIT 1
`

func (q *Queries) GetClass(ctx context.Context, id int64) (Class, error) {
	row := q.db.QueryRowContext(ctx, getClass, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HomeroomTeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClasses = `-- name: ListClasses :many
SELECT id, name, homeroom_teacher_id, created_at, updated_at FROM classes
ORDER BY id
`

func (q *Queries) ListClasses(ctx context.Context) ([]Class, error) {
	rows, err := q.db.QueryContext(ctx, listClasses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Class{}
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.HomeroomTeacherID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes
SET name = ?, homeroom_teacher_id = ?
WHERE id = ?
RETURNING id, name, homeroom_teacher_id, created_at, updated_at
`

type UpdateClassParams struct {
	Name              string `json:"name"`
	HomeroomTeacherID *int64 `json:"homeroom_teacher_id"`
	ID                int64  `json:"id"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRowContext(ctx, updateClass, arg.Name, arg.HomeroomTeacherID, arg.ID)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.HomeroomTeacherID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
