// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mapping.sql

package db

import (
	"context"
	"database/sql"
)

const assignStudentToClass = `-- name: AssignStudentToClass :exec
INSERT INTO class_student_mapping (student_id, class_id)
VALUES (?, ?)
ON CONFLICT(student_id) DO UPDATE SET class_id = exlcuded.class_id
`

type AssignStudentToClassParams struct {
	StudentID int64 `json:"student_id"`
	ClassID   int64 `json:"class_id"`
}

// upsert
func (q *Queries) AssignStudentToClass(ctx context.Context, arg AssignStudentToClassParams) error {
	_, err := q.db.ExecContext(ctx, assignStudentToClass, arg.StudentID, arg.ClassID)
	return err
}

const createTeacherAssignment = `-- name: CreateTeacherAssignment :one
INSERT INTO teaching_assignments (class_id, subject_id, teacher_id)
VALUES (?, ?, ?)
RETURNING id, class_id, subject_id, teacher_id
`

type CreateTeacherAssignmentParams struct {
	ClassID   int64 `json:"class_id"`
	SubjectID int64 `json:"subject_id"`
	TeacherID int64 `json:"teacher_id"`
}

func (q *Queries) CreateTeacherAssignment(ctx context.Context, arg CreateTeacherAssignmentParams) (TeachingAssignment, error) {
	row := q.db.QueryRowContext(ctx, createTeacherAssignment, arg.ClassID, arg.SubjectID, arg.TeacherID)
	var i TeachingAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.SubjectID,
		&i.TeacherID,
	)
	return i, err
}

const deleteTeacherAssignment = `-- name: DeleteTeacherAssignment :one
DELETE FROM teaching_assignments
WHERE id  = ?
RETURNING id, class_id, subject_id, teacher_id
`

func (q *Queries) DeleteTeacherAssignment(ctx context.Context, id int64) (TeachingAssignment, error) {
	row := q.db.QueryRowContext(ctx, deleteTeacherAssignment, id)
	var i TeachingAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.SubjectID,
		&i.TeacherID,
	)
	return i, err
}

const getStudentMappingById = `-- name: GetStudentMappingById :one
SELECT id, class_id, student_id FROM class_student_mapping
WHERE id = ?
`

func (q *Queries) GetStudentMappingById(ctx context.Context, id int64) (ClassStudentMapping, error) {
	row := q.db.QueryRowContext(ctx, getStudentMappingById, id)
	var i ClassStudentMapping
	err := row.Scan(&i.ID, &i.ClassID, &i.StudentID)
	return i, err
}

const getTeachingAssignmentById = `-- name: GetTeachingAssignmentById :one
SELECT id, class_id, subject_id, teacher_id FROM teaching_assignments
WHERE id = ?
`

func (q *Queries) GetTeachingAssignmentById(ctx context.Context, id int64) (TeachingAssignment, error) {
	row := q.db.QueryRowContext(ctx, getTeachingAssignmentById, id)
	var i TeachingAssignment
	err := row.Scan(
		&i.ID,
		&i.ClassID,
		&i.SubjectID,
		&i.TeacherID,
	)
	return i, err
}

const listStudentMappings = `-- name: ListStudentMappings :many
SELECT id, class_id, student_id FROM class_student_mapping
WHERE student_id = ?
ORDER BY id
`

func (q *Queries) ListStudentMappings(ctx context.Context, studentID int64) ([]ClassStudentMapping, error) {
	rows, err := q.db.QueryContext(ctx, listStudentMappings, studentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ClassStudentMapping{}
	for rows.Next() {
		var i ClassStudentMapping
		if err := rows.Scan(&i.ID, &i.ClassID, &i.StudentID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeachingAssignments = `-- name: ListTeachingAssignments :many
SELECT id, class_id, subject_id, teacher_id FROM teaching_assignments
WHERE teacher_id = ?
ORDER BY id
`

func (q *Queries) ListTeachingAssignments(ctx context.Context, teacherID int64) ([]TeachingAssignment, error) {
	rows, err := q.db.QueryContext(ctx, listTeachingAssignments, teacherID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeachingAssignment{}
	for rows.Next() {
		var i TeachingAssignment
		if err := rows.Scan(
			&i.ID,
			&i.ClassID,
			&i.SubjectID,
			&i.TeacherID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeStudentFromClass = `-- name: RemoveStudentFromClass :execresult
DELETE FROM class_student_mapping
WHERE student_id = ?
`

func (q *Queries) RemoveStudentFromClass(ctx context.Context, studentID int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, removeStudentFromClass, studentID)
}
