// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	// upsert
	AssignStudentToClass(ctx context.Context, arg AssignStudentToClassParams) error
	CreateClass(ctx context.Context, arg CreateClassParams) (Class, error)
	// SELECT
	//     s.id,
	//     s.first_name,
	//     s.last_name,
	//     s.email,
	//     s.date_of_birth,
	//     s.created_at,
	//     s.updated_at,
	//     c.name AS class_name
	// FROM students s
	// LEFT JOIN class_student_mapping csmap ON csmap.student_id = s.id
	// LEFT JOIN classes c ON c.id = csmap.class_id
	// ORDER BY s.id;
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error)
	CreateTeacherAssignment(ctx context.Context, arg CreateTeacherAssignmentParams) (TeachingAssignment, error)
	DeleteClass(ctx context.Context, id int64) (Class, error)
	DeleteStudent(ctx context.Context, id int64) (Student, error)
	DeleteTeacher(ctx context.Context, id int64) (Teacher, error)
	DeleteTeacherAssignment(ctx context.Context, id int64) (TeachingAssignment, error)
	GetClass(ctx context.Context, id int64) (Class, error)
	GetStudent(ctx context.Context, id int64) (Student, error)
	GetStudentMappingById(ctx context.Context, id int64) (ClassStudentMapping, error)
	GetSubjectByName(ctx context.Context, name string) (Subject, error)
	GetTeacher(ctx context.Context, id int64) (Teacher, error)
	GetTeachingAssignmentById(ctx context.Context, id int64) (TeachingAssignment, error)
	ListClasses(ctx context.Context) ([]Class, error)
	ListStudentMappings(ctx context.Context, studentID int64) ([]ClassStudentMapping, error)
	// SELECT
	//     s.id,
	//     s.first_name,
	//     s.last_name,
	//     s.email,
	//     s.date_of_birth,
	//     s.created_at,
	//     s.updated_at,
	//     c.name AS class_name
	// FROM students s
	// LEFT JOIN class_student_mapping csmap ON csmap.student_id = s.id
	// LEFT JOIN classes c ON c.id = csmap.class_id
	// WHERE s.id = ?
	// LIMIT 1;
	ListStudents(ctx context.Context) ([]Student, error)
	ListTeachers(ctx context.Context) ([]Teacher, error)
	ListTeachingAssignments(ctx context.Context, teacherID int64) ([]TeachingAssignment, error)
	RemoveStudentFromClass(ctx context.Context, studentID int64) (sql.Result, error)
	UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error)
	UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error)
	UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error)
}

var _ Querier = (*Queries)(nil)
