// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: students.sql

package db

import (
	"context"
)

const createStudent = `-- name: CreateStudent :one

INSERT INTO students (first_name, last_name, email, date_of_birth)
VALUES (?, ?, ?, ?)
RETURNING id, first_name, last_name, email, date_of_birth, created_at, updated_at
`

type CreateStudentParams struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	DateOfBirth string `json:"date_of_birth"`
}

// SELECT
//
//	s.id,
//	s.first_name,
//	s.last_name,
//	s.email,
//	s.date_of_birth,
//	s.created_at,
//	s.updated_at,
//	c.name AS class_name
//
// FROM students s
// LEFT JOIN class_student_mapping csmap ON csmap.student_id = s.id
// LEFT JOIN classes c ON c.id = csmap.class_id
// ORDER BY s.id;
func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, createStudent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.DateOfBirth,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStudent = `-- name: DeleteStudent :one
DELETE FROM students
WHERE id = ?
RETURNING id, first_name, last_name, email, date_of_birth, created_at, updated_at
`

func (q *Queries) DeleteStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRowContext(ctx, deleteStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStudent = `-- name: GetStudent :one
SELECT id, first_name, last_name, email, date_of_birth, created_at, updated_at FROM students
WHERE students.id = ?
LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id int64) (Student, error) {
	row := q.db.QueryRowContext(ctx, getStudent, id)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStudents = `-- name: ListStudents :many

SELECT id, first_name, last_name, email, date_of_birth, created_at, updated_at FROM students
`

// SELECT
//
//	s.id,
//	s.first_name,
//	s.last_name,
//	s.email,
//	s.date_of_birth,
//	s.created_at,
//	s.updated_at,
//	c.name AS class_name
//
// FROM students s
// LEFT JOIN class_student_mapping csmap ON csmap.student_id = s.id
// LEFT JOIN classes c ON c.id = csmap.class_id
// WHERE s.id = ?
// LIMIT 1;
func (q *Queries) ListStudents(ctx context.Context) ([]Student, error) {
	rows, err := q.db.QueryContext(ctx, listStudents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Student{}
	for rows.Next() {
		var i Student
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStudent = `-- name: UpdateStudent :one
UPDATE students
SET
    first_name = ?,
    last_name = ?,
    email = ?,
    date_of_birth = ?
WHERE id = ?
RETURNING id, first_name, last_name, email, date_of_birth, created_at, updated_at
`

type UpdateStudentParams struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	DateOfBirth string `json:"date_of_birth"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateStudent(ctx context.Context, arg UpdateStudentParams) (Student, error) {
	row := q.db.QueryRowContext(ctx, updateStudent,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.DateOfBirth,
		arg.ID,
	)
	var i Student
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
