// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teachers.sql

package db

import (
	"context"
)

const createTeacher = `-- name: CreateTeacher :one
INSERT INTO teachers (first_name, last_name, email, date_of_birth)
VALUES (?, ?, ?, ?)
RETURNING id, first_name, last_name, email, date_of_birth, created_at, updated_at
`

type CreateTeacherParams struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	DateOfBirth string `json:"date_of_birth"`
}

func (q *Queries) CreateTeacher(ctx context.Context, arg CreateTeacherParams) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, createTeacher,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.DateOfBirth,
	)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTeacher = `-- name: DeleteTeacher :one
DELETE FROM teachers
WHERE id = ?
RETURNING id, first_name, last_name, email, date_of_birth, created_at, updated_at
`

func (q *Queries) DeleteTeacher(ctx context.Context, id int64) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, deleteTeacher, id)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeacher = `-- name: GetTeacher :one
SELECT id, first_name, last_name, email, date_of_birth, created_at, updated_at FROM teachers
WHERE teachers.id = ?
LIMIT 1
`

func (q *Queries) GetTeacher(ctx context.Context, id int64) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, getTeacher, id)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeachers = `-- name: ListTeachers :many
SELECT id, first_name, last_name, email, date_of_birth, created_at, updated_at FROM teachers
`

func (q *Queries) ListTeachers(ctx context.Context) ([]Teacher, error) {
	rows, err := q.db.QueryContext(ctx, listTeachers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Teacher{}
	for rows.Next() {
		var i Teacher
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.Email,
			&i.DateOfBirth,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTeacher = `-- name: UpdateTeacher :one
UPDATE teachers
SET
    first_name = ?,
    last_name = ?,
    email = ?,
    date_of_birth = ?
WHERE id = ?
RETURNING id, first_name, last_name, email, date_of_birth, created_at, updated_at
`

type UpdateTeacherParams struct {
	FirstName   string `json:"first_name"`
	LastName    string `json:"last_name"`
	Email       string `json:"email"`
	DateOfBirth string `json:"date_of_birth"`
	ID          int64  `json:"id"`
}

func (q *Queries) UpdateTeacher(ctx context.Context, arg UpdateTeacherParams) (Teacher, error) {
	row := q.db.QueryRowContext(ctx, updateTeacher,
		arg.FirstName,
		arg.LastName,
		arg.Email,
		arg.DateOfBirth,
		arg.ID,
	)
	var i Teacher
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Email,
		&i.DateOfBirth,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
